// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc.proto

package protobuf_grpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TestEnum int32

const (
	TestEnum_multiplication TestEnum = 0
	TestEnum_division       TestEnum = 1
)

var TestEnum_name = map[int32]string{
	0: "multiplication",
	1: "division",
}

var TestEnum_value = map[string]int32{
	"multiplication": 0,
	"division":       1,
}

func (x TestEnum) String() string {
	return proto.EnumName(TestEnum_name, int32(x))
}

func (TestEnum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_bedfbfc9b54e5600, []int{0}
}

type Handler struct {
	Task                 TestEnum `protobuf:"varint,1,opt,name=task,proto3,enum=protobuf_grpc.TestEnum" json:"task,omitempty"`
	FirstValue           int32    `protobuf:"varint,2,opt,name=firstValue,proto3" json:"firstValue,omitempty"`
	SecondValue          int32    `protobuf:"varint,3,opt,name=secondValue,proto3" json:"secondValue,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Handler) Reset()         { *m = Handler{} }
func (m *Handler) String() string { return proto.CompactTextString(m) }
func (*Handler) ProtoMessage()    {}
func (*Handler) Descriptor() ([]byte, []int) {
	return fileDescriptor_bedfbfc9b54e5600, []int{0}
}

func (m *Handler) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Handler.Unmarshal(m, b)
}
func (m *Handler) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Handler.Marshal(b, m, deterministic)
}
func (m *Handler) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Handler.Merge(m, src)
}
func (m *Handler) XXX_Size() int {
	return xxx_messageInfo_Handler.Size(m)
}
func (m *Handler) XXX_DiscardUnknown() {
	xxx_messageInfo_Handler.DiscardUnknown(m)
}

var xxx_messageInfo_Handler proto.InternalMessageInfo

func (m *Handler) GetTask() TestEnum {
	if m != nil {
		return m.Task
	}
	return TestEnum_multiplication
}

func (m *Handler) GetFirstValue() int32 {
	if m != nil {
		return m.FirstValue
	}
	return 0
}

func (m *Handler) GetSecondValue() int32 {
	if m != nil {
		return m.SecondValue
	}
	return 0
}

type Test struct {
	Label                string   `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Type                 int32    `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	Reps                 int64    `protobuf:"varint,3,opt,name=reps,proto3" json:"reps,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Test) Reset()         { *m = Test{} }
func (m *Test) String() string { return proto.CompactTextString(m) }
func (*Test) ProtoMessage()    {}
func (*Test) Descriptor() ([]byte, []int) {
	return fileDescriptor_bedfbfc9b54e5600, []int{1}
}

func (m *Test) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Test.Unmarshal(m, b)
}
func (m *Test) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Test.Marshal(b, m, deterministic)
}
func (m *Test) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Test.Merge(m, src)
}
func (m *Test) XXX_Size() int {
	return xxx_messageInfo_Test.Size(m)
}
func (m *Test) XXX_DiscardUnknown() {
	xxx_messageInfo_Test.DiscardUnknown(m)
}

var xxx_messageInfo_Test proto.InternalMessageInfo

func (m *Test) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *Test) GetType() int32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *Test) GetReps() int64 {
	if m != nil {
		return m.Reps
	}
	return 0
}

type Result struct {
	Result               int32    `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Result) Reset()         { *m = Result{} }
func (m *Result) String() string { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()    {}
func (*Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_bedfbfc9b54e5600, []int{2}
}

func (m *Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Result.Unmarshal(m, b)
}
func (m *Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Result.Marshal(b, m, deterministic)
}
func (m *Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result.Merge(m, src)
}
func (m *Result) XXX_Size() int {
	return xxx_messageInfo_Result.Size(m)
}
func (m *Result) XXX_DiscardUnknown() {
	xxx_messageInfo_Result.DiscardUnknown(m)
}

var xxx_messageInfo_Result proto.InternalMessageInfo

func (m *Result) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

type Reply struct {
	Reply                string   `protobuf:"bytes,1,opt,name=reply,proto3" json:"reply,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Reply) Reset()         { *m = Reply{} }
func (m *Reply) String() string { return proto.CompactTextString(m) }
func (*Reply) ProtoMessage()    {}
func (*Reply) Descriptor() ([]byte, []int) {
	return fileDescriptor_bedfbfc9b54e5600, []int{3}
}

func (m *Reply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Reply.Unmarshal(m, b)
}
func (m *Reply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Reply.Marshal(b, m, deterministic)
}
func (m *Reply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Reply.Merge(m, src)
}
func (m *Reply) XXX_Size() int {
	return xxx_messageInfo_Reply.Size(m)
}
func (m *Reply) XXX_DiscardUnknown() {
	xxx_messageInfo_Reply.DiscardUnknown(m)
}

var xxx_messageInfo_Reply proto.InternalMessageInfo

func (m *Reply) GetReply() string {
	if m != nil {
		return m.Reply
	}
	return ""
}

func init() {
	proto.RegisterEnum("protobuf_grpc.TestEnum", TestEnum_name, TestEnum_value)
	proto.RegisterType((*Handler)(nil), "protobuf_grpc.Handler")
	proto.RegisterType((*Test)(nil), "protobuf_grpc.Test")
	proto.RegisterType((*Result)(nil), "protobuf_grpc.Result")
	proto.RegisterType((*Reply)(nil), "protobuf_grpc.Reply")
}

func init() { proto.RegisterFile("grpc.proto", fileDescriptor_bedfbfc9b54e5600) }

var fileDescriptor_bedfbfc9b54e5600 = []byte{
	// 295 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x51, 0xcd, 0x4b, 0x3b, 0x31,
	0x14, 0xec, 0xfe, 0xda, 0x6d, 0xf7, 0xf7, 0xd4, 0x22, 0xcf, 0x5a, 0x4b, 0x41, 0x59, 0xf6, 0x54,
	0x54, 0xf6, 0x50, 0x0f, 0x82, 0x67, 0x45, 0xcf, 0xb1, 0x78, 0x95, 0xfd, 0x48, 0x25, 0x98, 0x66,
	0x43, 0x3e, 0xc4, 0x1e, 0xfd, 0xcf, 0x25, 0xaf, 0x5d, 0xa8, 0xd5, 0x53, 0x66, 0x86, 0xc9, 0xbc,
	0xcc, 0x0b, 0xc0, 0x9b, 0xd1, 0x55, 0xae, 0x4d, 0xe3, 0x1a, 0x3c, 0xa2, 0xa3, 0xf4, 0xcb, 0xd7,
	0x20, 0x66, 0x9f, 0x30, 0x78, 0x2a, 0x54, 0x2d, 0xb9, 0xc1, 0x2b, 0xe8, 0xb9, 0xc2, 0xbe, 0x4f,
	0xa2, 0x34, 0x9a, 0x0d, 0xe7, 0x67, 0xf9, 0x0f, 0x63, 0xbe, 0xe0, 0xd6, 0x3d, 0x28, 0xbf, 0x62,
	0x64, 0xc2, 0x0b, 0x80, 0xa5, 0x30, 0xd6, 0xbd, 0x14, 0xd2, 0xf3, 0xc9, 0xbf, 0x34, 0x9a, 0xc5,
	0x6c, 0x47, 0xc1, 0x14, 0x0e, 0x2c, 0xaf, 0x1a, 0x55, 0x6f, 0x0c, 0x5d, 0x32, 0xec, 0x4a, 0xd9,
	0x3d, 0xf4, 0x42, 0x26, 0x8e, 0x20, 0x96, 0x45, 0xc9, 0x25, 0xcd, 0xfd, 0xcf, 0x36, 0x04, 0x11,
	0x7a, 0x6e, 0xad, 0xdb, 0x64, 0xc2, 0x41, 0x33, 0x5c, 0x5b, 0x0a, 0xeb, 0x32, 0xc2, 0x59, 0x0a,
	0x7d, 0xc6, 0xad, 0x97, 0x0e, 0xc7, 0xd0, 0x37, 0x84, 0x28, 0x28, 0x66, 0x5b, 0x96, 0x9d, 0x43,
	0xcc, 0xb8, 0x96, 0xeb, 0x30, 0xc8, 0x04, 0xd0, 0x0e, 0x22, 0x72, 0x79, 0x0d, 0x49, 0x5b, 0x0d,
	0x11, 0x86, 0x2b, 0x2f, 0x9d, 0xd0, 0x52, 0x54, 0x85, 0x13, 0x8d, 0x3a, 0xee, 0xe0, 0x21, 0x24,
	0xb5, 0xf8, 0x10, 0x36, 0xb0, 0x68, 0xfe, 0x15, 0x01, 0xb0, 0xc6, 0x3b, 0xfe, 0xe8, 0x45, 0xcd,
	0xf1, 0x16, 0x92, 0x67, 0xae, 0x6a, 0xea, 0x71, 0xf2, 0xc7, 0xc2, 0xa6, 0xa3, 0x3d, 0x91, 0x5e,
	0x92, 0x75, 0xf0, 0x0e, 0x06, 0xcc, 0xab, 0x45, 0xd8, 0xe4, 0x78, 0xcf, 0xb2, 0xfd, 0x8e, 0xe9,
	0xe9, 0xaf, 0xab, 0x54, 0xa7, 0x53, 0xf6, 0x49, 0xbf, 0xf9, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x28,
	0x8f, 0x43, 0x96, 0xd6, 0x01, 0x00, 0x00,
}
